### ISSUE TITLE
Smartbrainlib requires forge 47.1.4x

### ISSUE THREAD

**Issue by Devilswarchild** [Tslat/SmartBrainLib#45]
mc 1.20.1
Forge 47.1.3
mod: smartbrainlib-forge-1.20.1-1.12.jar

not sure what happened? either you purposely uploaded the wrong mod file or were unaware that anything above forge 47.1.3 was currently broken beyond repair. but the latest update is calling for forge 47.1.4x instead of 47.1.3. just giving you a heads up. I had to downgrade to get it working again.

**Comment by Tslat** [comment]
This is a bit of a complex situation because of forge breaking stuff

I might add some more information to the file on curseforge or something, but I'm always going to be between a rock and a hard place

SBL-Forge-1.20.1-1.12 is specifically for the newer forge versions (47.1.28 and above), with the changes necessary to make it work with Forge's changes
You should be using SBL-(Neo)Forge for anything underneath that

**Comment by Tslat** [comment]
I've added this comment to the file, and renamed it to Broken Forge to help clarify

![image](https://github.com/Tslat/SmartBrainLib/assets/7098525/d11f59f9-4fb3-40c8-9da5-61956c7f9559)

**Comment by Tslat** [comment]
Yep

Like I said, it's a bit of a tricky situation
This file isn't for you, if you're staying on 47.1.3 or below, or on NeoForge
